### ISSUE TITLE
can we add  extension to make unfollow to pages and people in Facebook 

### ISSUE THREAD

**Issue by ghost** [harshita214/Chrome-Extension#214]
can we enhance it to become for all social media like LinkedIn, youtube
can you assign it to me but it takes time because I'm a beginner at it

**Comment by Spring-dot** [comment]
@GAbdulWahab can you explain it more? Are you GSSoC participant?

**Comment by GAbdulWahab** [comment]
@Spring-dot yes, I am in GSSOC'22 and I'm a beginner :)
Well, I will explain to you, due to the diversity and increase of content on Facebook pages, people follow more so that the page is filled with things that are not useful, so he resorts to disliking more pages and people with useful content and this takes more time, especially since the number of pages is many, In the extension, you will do this thing automatically

like this  https://chrome.google.com/webstore/detail/unfollow-everything-on-fa/ogjpnnnookdhieoajbecmmgpgkeepnao?msclkid=cd632f0bad0011ec8af630dd05550027

**Comment by GAbdulWahab** [comment]
@Spring-dot   and I want to make one extension control in all social media especially in button in unfollowing :)

**Comment by harshita214** [comment]
@GAbdulWahab are you going to build a replica of [this](https://chrome.google.com/webstore/detail/unfollow-everything-on-fa/ogjpnnnookdhieoajbecmmgpgkeepnao?msclkid=cd632f0bad0011ec8af630dd05550027) extension



> @Spring-dot and I want to make one extension control in all social media especially in button in unfollowing :)

>> Also can you explain this idea more briefly

**Comment by GAbdulWahab** [comment]
@harshita214  yes I will try to make like this extension  
and will enhance it to be capable with another social media

**Comment by harshita214** [comment]
@GAbdulWahab Sure go ahead
All the best 👍

**Comment by GAbdulWahab** [comment]
@harshita214  I have this week's Midterm Exams, I will start in it after this week

**Comment by whiteHatpro** [comment]
update?

**Comment by komalsoni4** [comment]
hey , Please assign this issue to me

**Comment by whiteHatpro** [comment]
@komalsoni4 all the best
Make sure you keep me posted about the updates

**Comment by komalsoni4** [comment]
ya sure

**Comment by Kanika2772002** [comment]
Hey @harshita214  can you please assign this task to me?

**Comment by harshita214** [comment]
@komalsoni4 unassigning the issue to you

@Kanika2772002 assigning you 
All the best 👍

**Comment by weberankit** [comment]
Can I work on this issue
